name = "MusicTransformer"
uuid = "0f5573e1-0924-4984-b57b-b82521c092bc"
authors = ["Vasanth <vasanth.mani.vasi.2@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
