[unconditional_model_16]
host = "Google"
description = "Music Transformer with self-attention."
link = "https://github.com/magenta/magenta/tree/main/magenta/models/score2perf"
num_layers = 16
heads = 8
depth = 512
ffn_depth = 2048
model_type = "unconditional"
name = "Unconditional Music Transformer"
url = "https://docs.google.com/uc?id=1ErVsPpndLL45b3RHbC4RFQYkG4zu-vih&export=download"
checksum = "d9d39efb9ba7b07ecd7e1eeebe605c905739664eb5ee9a7b6c5b3981139722fe"

[melody_conditioned_model_16]
host = "Google"
description = "Melody Conditioned Music Transformer with self-attention."
link = "https://github.com/magenta/magenta/tree/main/magenta/models/score2perf"
num_layers = 16
heads = 8
depth = 512
ffn_depth = 2048
model_type = "melodyconditioned"
name = "Melody Conditioned Music Transformer"
url = "https://docs.google.com/uc?id=1b4W_vU3BM0PaeNHGqMQizLFWqTxXhGQw&export=download"
checksum = "377b17f31360dbfa44395d621fee2533a3b9912573b3428c5dd1d6e8518d7cce"

[perfrnn]
host = "Google"
description = "Baseline PerformanceRNN"
link = "https://github.com/magenta/magenta/tree/master/magenta/models/performance_rnn"
num_layers = 3
input_dims = 356
lstm_units = 512
velocity_bins = 0
model_type = "perfrnn"
name = "PerformanceRNN"
url = "https://drive.google.com/u/1/uc?id=1z7mhFoRyaxZVb3xo5X3pwQYD8sa_m_Ce&export=download"
checksum = "68ac1b810cfa42bdc1a6d08974f8043a5ec9344a75f7e1f1abca229159d78ab8"

[perfrnn_dynamics]
host = "Google"
description = "PerformanceRNN with dynamics"
link = "https://github.com/magenta/magenta/tree/master/magenta/models/performance_rnn"
num_layers = 3
input_dims = 388
lstm_units = 512
velocity_bins = 32
model_type = "perfrnn"
name = "PerformanceRNN with dynamics"
url = "https://drive.google.com/u/1/uc?id=1qtBdZCpYwwu-5xqoKtR-6io4cqfp4ZYl&export=download"
checksum = "a57b47da53c9a5e0823ff881909a8f6c74f1e60b2a347587036d344a249fcfdd"
