[unconditional_model_16]
host = "Google"
description = "Music Transformer with self-attention"
link = "https://github.com/magenta/magenta/tree/main/magenta/models/score2perf"
num_layers = 16
heads = 8
depth = 512
ffn_depth = 2048
model_type = "unconditional"
name = "Baseline Music Transformer"
url = "https://docs.google.com/uc?id=1ErVsPpndLL45b3RHbC4RFQYkG4zu-vih&export=download"
checksum = "d9d39efb9ba7b07ecd7e1eeebe605c905739664eb5ee9a7b6c5b3981139722fe"
